### ISSUE TITLE
outlabel background color not working

### ISSUE THREAD

**Issue by lvostinar** [energiency/chartjs-plugin-piechart-outlabels#12]
I am using outlabel plugin with chart.js version 4.2.1 and background color is not working. Looking at the code, the backgroundColor is not used at all anymore (compared to original outlabel plugin). So, for me, the outlabel has no background color. Is this behavior on purpose?

**Comment by rom3N123** [comment]
same here

**Comment by jledentu** [comment]
Hi, the behaviour was actually intended in our specific case, because we didn't need this. But we forgot to adapt the sample and documentation.

I fixed this in 1.3.3 release by fixing/restoring the behavior of the original library. `backgroundColor`, `borderColor`, `borderWidth`, `borderRadius` are now working.
